### ISSUE TITLE
Shadow bug

### ISSUE THREAD

**Issue by MarkuBu** [duane-r/intersect_light#1]
Hi Duane, can you add a heightmap check like in fun_caves to remove the shadows from the surface?

**Comment by duane-r** [comment]
What shadows are you seeing? Intersect's caves are a lot simpler than v6. I've never seen them cause lighting issues. Can you give me a seed and location?

**Comment by MarkuBu** [comment]
Hm, it is difficult to reproduce the bug. And it seems that intersect_light works fine. I flew around only with intersect_light mod active, but I could not find any shadows. Only if I have fun_caves v6 mod loaded I can find shadows, but I can not reproduce them if I create an new map with the same parameters.

This screenshot is made with fun_caves v6 and without intersect_light

![screenshot_20160502_105851](https://cloud.githubusercontent.com/assets/16163058/14950917/b2bb0882-1055-11e6-8179-3f92de49e6b9.png)

**Comment by duane-r** [comment]
Well, it's not an intersect problem, anyway.

**Comment by MarkuBu** [comment]
I'm sorry, I was to hurry. But it seems to be a fun_caves bug. I will report an new issue if I'm shure
